### ISSUE TITLE
API to get all GlyGen Draft BCOs ...

### ISSUE THREAD

**Issue by rykahsay** [biocompute-objects/bco_api#153]
Please give API call example to get all GlyGen draft BCOs. 

I thought this was the closest but it is not working. 

curl -X POST "https://biocomputeobject.org/api/objects/search/" -H  "accept: application/json" -H  "Authorization: Token xxxxxxxxxxxx" -H  "Content-Type: application/json" -H  "X-CSRFToken: S135wMoljfCWOTxf3PE32o7whbNbs4IGassqzB7jvFiaWg0LDHkf5th0A4RVIBJD" -d "{\"prefix\": \"GLY\"}"

**Comment by HadleyKing** [comment]
@rykahsay 
Apologies. Documentation for that endpoint has not been published. I will make that a hotfix this week hopefully. It was only ever used by the UI so I didn't have to document it yet. 
I did this on my local test server so you will have to update some things. Their are two required values:

1. `type`:  can be one of 3 different values => `mine | prefix | bco_id`
2. `search`:  
  - This should be an empty string if you are doing the `mine` search as that is for "My BCOs"
  - For `prefix` it should be the name of the prefix.
  - For `bco_id` it should be some substring that is present in the desired `bco_id` or SET of `bco_id`s

An example of what you need to run is the following:
 - in `shell`:
```shell
curl -X POST "http://localhost:8000/api/objects/search/" -H  "accept: application/json" -H  "Authorization: Token c400a6076a2dfe7e9906ab86c6ad4574d1d60e03" -H  "Content-Type: application/json" -d "{\"POST_api_objects_search\":[{\"type\": \"prefix\",\"search\": \"TEST\"}]}"
```

- in `javascript`:
```javascript
axios.post("http://localhost:8000/api/objects/search/", {
  "POST_api_objects_search":[
    {
      "type": "prefix",
      "search": "TEST"
    }
  ]
}, {
    headers: {
      "Authorization": "Token c400a6076a2dfe7e9906ab86c6ad4574d1d60e03,
      "Content-Type": "application/json"
    }
});
```


If this solves your blocker please feel free to close the issue, otherwise let me know what is still missing.

**Comment by rykahsay** [comment]
@HadleyKing -- I don't understand, are you saying this working only on your localhost and will be available on the server in a week? If that is the case, I really don't have a week on my time line. Is there something you can do immediately?

**Comment by HadleyKing** [comment]
> @HadleyKing -- I don't understand, are you saying this working only on your localhost and will be available on the server in a week? If that is the case, I really don't have a week on my time line. Is there something you can do immediately?

No. The above examples are in PRODUCTION now.... I just ran it on my localhost so I would not expose any tokens or credentials. 

The **hot fix** comment was about the DOCUMENTATION for this API.
