### ISSUE TITLE
Develop rules for BCO scoring

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#311]
[Commit](407b18c1ccb5911ec63e68e16f3e73fe9755b739) for first attribute = length of usability domain text.

**Comment by kee007ney** [comment]
| Criteria | Score |
|----------|-------|
| Field length modifier | x1.2 |
| Error Domain exists | +5 |
| Each Parametric object | x1.1 |
| Each reviewer object up to 5 | +1 |

Scoring might look like this (but with a more polished UI instead of text-based):


0---------------1---------------∞
----------------------^                   Your score: 24


Where 0 - 1 is unvalidated territory, and anything above 1 is validated and getting a score.

**Comment by kee007ney** [comment]
Possibly break it into two scores: BCO score and FINDability score. FINDability looks for things like resolvable addresses (Chinewoke's idea).

**Comment by ChinweokeO** [comment]
Measurable Attributes
-  Check for duplicates. For example in intermediate I/O steps, *this idea will be finetuned as some steps may have inputs from a previous step's output
- Open Source validation when it comes to resolvable addresses/URLs
- Usage metrics*: May not be implementable, but the idea is to gauge how people are interacting with a certain BCO

**Comment by HadleyKing** [comment]
https://github.com/biocompute-objects/bco_api/issues/330

**Comment by ChinweokeO** [comment]
#328
